export const SIDEBAR_OPEN = 'SIDEBAR_OPEN';
export const SIDEBAR_CLOSE = 'SIDEBAR_CLOSE';
export const GET_RECIPES_BEGIN = 'GET_RECIPES_BEGIN';
export const GET_RECIPES_SUCCESS = 'GET_RECIPES_SUCCESS';
export const GET_RECIPES_ERROR = 'GET_RECIPES_ERROR';
export const GET_SINGLE_RECIPE_BEGIN = 'GET_SINGLE_RECIPE_BEGIN';
export const GET_SINGLE_RECIPE_SUCCESS = 'GET_SINGLE_RECIPE_SUCCESS';
export const GET_SINGLE_RECIPE_ERROR = 'GET_SINGLE_RECIPE_ERROR';
// filter actions
export const LOAD_RECIPES = 'LOAD_RECIPES';
export const UPDATE_FILTERS = 'UPDATE_FILTERS';
export const FILTER_RECIPES = 'FILTER_RECIPES';
export const CLEAR_FILTERS = 'CLEAR_FILTERS';
